image: maven:3.9-eclipse-temurin-21

stages:
  - build
  - test

build:
  stage: build
  script:
    - java -version
    - mvn -B -DskipTests clean package

test:
  stage: test
  script:
    - java -version
    - mvn -B test
