image: maven:3.9-eclipse-temurin-21

stages:
  - build
  - test
  - docker

build:
  stage: build
  script:
    - java -version
    - mvn -B -DskipTests clean package

test:
  stage: test
  script:
    - java -version
    - mvn -B test

docker-build:
  stage: docker
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker version
    - docker build -t shoplite-api-gateway:ci ./api-gateway
    - docker build -t shoplite-config-server:ci ./config-server
    - docker build -t shoplite-customer-service:ci ./customer-service
    - docker build -t shoplite-discovery-server:ci ./discovery-server
    - docker build -t shoplite-order-service:ci ./order-service
    - docker build -t shoplite-product-service:ci ./product-service