# --- Désactivation TEMPORAIRE de la DB ---
spring.datasource.url=
spring.datasource.driver-class-name=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Empêche Spring de tenter de créer/valider une source de données
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# --- Config Server ---
spring.application.name=order-service
server.port=0
spring.config.import=optional:configserver:http://localhost:8888

# --- Eureka ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


